name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Read a file from another repository
    - uses: actions/checkout@v3
      with: 
        repository: FredericoR/workflow-test-repository
        ref: main
    - name: cat
      run: cat ./README.md
  
  job-2:
    
    runs-on: windows-latest
    
    steps:
    - name: Print values
      run: dir
    - name: Display Date
      run: "Get-Date -DisplayHint Date"
