name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      uses: docker://hello-world:latest
  
  job-2:
    
    runs-on: windows-latest
    
    steps:
    - name: Print values
      run: dir
    - name: Display Date
      run: "Get-Date -DisplayHint Date"
